version: "3.9"
services:
  mysql:
    image: mariadb:latest
    container_name: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  mariadb_data: